[package]
name = "crankler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unrar = "0.4.4"
zip = "0.6.4"
qpdf = "0.1.5"
bruteforce = "0.2.1"